Repository code4romania/vic, pull requests merged in 2023-05, with the labels that each got.

#144 Feat[TEO-793] - Add translations to mobile project
  mobile/src/assets/locales/ro/translation.json
  mobile/src/components/AboutTeo.tsx
  mobile/src/components/LatestNews.tsx
  mobile/src/components/Statistics.tsx
  mobile/src/routes/Tabs.tsx
  mobile/src/screens/ActivityLog.tsx
  mobile/src/screens/ActivityLogs.tsx
  mobile/src/screens/AddActivityLog.tsx
  mobile/src/screens/CreateAccount.tsx
  mobile/src/screens/EditActivityLog.tsx
  mobile/src/screens/EditVolunteer.tsx
  mobile/src/screens/Event.tsx
  mobile/src/screens/Events.tsx
  mobile/src/screens/ForgotPassword.tsx
  mobile/src/screens/JoinEvent.tsx
  mobile/src/screens/JoinOrganization.tsx
  mobile/src/screens/Landing.tsx
  mobile/src/screens/Login.tsx
  mobile/src/screens/News.tsx
  mobile/src/screens/Organizations.tsx
  mobile/src/screens/Volunteer.tsx
  mobile/src/screens/VolunteerProfile.tsx
Labels: enhancement :rocket:, front-end

#142 FeatTEO-780] - Accounts setting page
  mobile/src/assets/locales/en/translation.json
  mobile/src/assets/locales/ro/translation.json
  mobile/src/assets/svg/bell.js
  mobile/src/assets/svg/identification.js
  mobile/src/assets/svg/information.js
  mobile/src/assets/svg/key.js
  mobile/src/assets/svg/logout.js
  mobile/src/assets/svg/user.js
  mobile/src/common/constants/setting-screens.ts
  mobile/src/common/enums/setting-routes.ts
  mobile/src/layouts/FormLayout.tsx
  mobile/src/layouts/PageLayout.tsx
  mobile/src/routes/Private.tsx
  mobile/src/screens/AccountData.tsx
  mobile/src/screens/ChangePassword.tsx
  mobile/src/screens/IdentityData.tsx
  mobile/src/screens/NotificationsSettings.tsx
  mobile/src/screens/Settings.tsx
Labels: enhancement :rocket:, front-end

#153 Feat[TEO-838] - Create User Profile
  mobile/src/assets/locales/ro/translation.json
  mobile/src/common/constants/sex-options.ts
  mobile/src/common/enums/sex.enum.ts
  mobile/src/common/theme/theme.json
  mobile/src/components/FormDatePicker.tsx
  mobile/src/components/FormInput.tsx
  mobile/src/components/FormSelect.tsx
  mobile/src/components/InlineLink.tsx
  mobile/src/screens/CreateAccount.tsx
  mobile/src/screens/CreateUser.tsx
Labels: enhancement :rocket:, front-end

#143 Feat[TEO-778] - View NGO Profile
  mobile/src/assets/images/event.png
  mobile/src/assets/images/logo.png
  mobile/src/assets/locales/ro/translation.json
  mobile/src/assets/svg/location.js
  mobile/src/assets/svg/users.js
  mobile/src/components/EventItem.tsx
  mobile/src/components/ProfileIntro.tsx
  mobile/src/components/ReadOnlyElement.tsx
  mobile/src/screens/OrganizationProfile.tsx
Labels: enhancement :rocket:, front-end

#150 Feat[TEO-774] - View List of NGO's
  mobile/src/assets/locales/ro/translation.json
  mobile/src/common/theme/theme.json
  mobile/src/screens/Organizations.tsx
Labels: enhancement :rocket:, front-end

#151 Feat[TEO-653] - View Volunteer Profile page
  mobile/package-lock.json
  mobile/package.json
  mobile/src/assets/locales/ro/translation.json
  mobile/src/common/utils/utils.ts
  mobile/src/components/OrganizationIdentity.tsx
  mobile/src/layouts/PageLayout.tsx
  mobile/src/screens/VolunteerProfile.tsx
Labels: enhancement :rocket:, front-end

#154 Feat[TEO-851] - Volunteer Page
  mobile/src/assets/locales/ro/translation.json
  mobile/src/assets/svg/chevron-right.js
  mobile/src/assets/svg/volunteer-clock.js
  mobile/src/assets/svg/volunteer-user.js
  mobile/src/common/theme/mappings.json
  mobile/src/common/theme/theme.json
  mobile/src/components/TopNavigationCard.tsx
  mobile/src/components/VolunteerCard.tsx
  mobile/src/screens/Volunteer.tsx
Labels: enhancement :rocket:, front-end

#155 Feat[TEO-844] - Join NGO Request Screen
  mobile/src/assets/locales/ro/translation.json
  mobile/src/common/constants/referral-options.ts
  mobile/src/common/enums/refferal.enum.ts
  mobile/src/components/FormInput.tsx
  mobile/src/routes/Drawer.tsx
  mobile/src/screens/JoinOrganization.tsx
Labels: enhancement :rocket:, front-end

#156 Feat[TEO-845] - Join NGO by Access Code Screen
  mobile/src/assets/locales/ro/translation.json
  mobile/src/assets/svg/info.js
  mobile/src/routes/Private.tsx
  mobile/src/screens/AccessCode.tsx
Labels: enhancement :rocket:, front-end

#160 Feat[TEO-855] - Edit Volunteer Profile
  mobile/src/assets/locales/ro/translation.json
  mobile/src/components/Button.tsx
  mobile/src/components/FormInput.tsx
  mobile/src/layouts/ModalLayout.tsx
  mobile/src/screens/EditVolunteer.tsx
Labels: enhancement :rocket:, front-end

#173 Feature[TEO-841] User identity Data integration
  backend/src/api/_mobile/user/dto/update-user-personal-data.dto.ts
  backend/src/api/_mobile/user/presenters/user-personal-data.presenter.ts
  backend/src/api/_mobile/user/presenters/user.presenter.ts
  backend/src/api/_mobile/user/user.controller.ts
  backend/src/migrations/1685017566505-AddUserPersonalData.ts
  backend/src/migrations/1685098784836-RemoveUniqueContraintOnSeries.ts
  backend/src/modules/user/entities/user-personal-data.entity.ts
  backend/src/modules/user/entities/user.entity.ts
  backend/src/modules/user/exceptions/exceptions.ts
  backend/src/modules/user/interfaces/regular-user-repository.interface.ts
  backend/src/modules/user/interfaces/user-personal-data-repository.interface.ts
  backend/src/modules/user/models/regular-user.model.ts
  backend/src/modules/user/models/user-personal-data.model.ts
  backend/src/modules/user/repositories/regular-user.repository.ts
  backend/src/modules/user/repositories/user-personal-data.repository.ts
  backend/src/modules/user/services/user-facade.service.ts
  backend/src/modules/user/user.module.ts
  backend/src/usecases/use-case.module.ts
  backend/src/usecases/user/update-user-personal-data.usecase.ts
  mobile/src/assets/locales/en/translation.json
  mobile/src/assets/locales/ro/translation.json
  mobile/src/common/constants/setting-screens.ts
  mobile/src/common/enums/setting-routes.ts
  mobile/src/common/errors/base-error.class.ts
  mobile/src/common/errors/entities/user.errors.ts
  mobile/src/common/errors/internal-errors.class.ts
  mobile/src/common/interfaces/user-profile.interface.ts
  mobile/src/routes/Private.tsx
  mobile/src/screens/IdentityData.tsx
  mobile/src/screens/PrivacyPolicy.tsx
  mobile/src/screens/Settings.tsx
  mobile/src/services/user/user.api.ts
  mobile/src/services/user/user.service.ts
Labels: back-end, enhancement :rocket:, front-end

#161 Feat[TEO-866] - Refactor Mobile Toasts
  mobile/App.tsx
  mobile/src/common/config/toast.tsx
Labels: front-end

#163 Bugfix[TEO-862] - Improper display of terms and conditions text
  mobile/src/assets/locales/ro/translation.json
  mobile/src/screens/CreateAccount.tsx
Labels: bug :bug:, front-end

#168 Bugfix[TEO-877]- Drawer cannot be accessed by pressing on the page header
  mobile/src/screens/Volunteer.tsx
Labels: bug :bug:

#165 Feat[TEO-870] - View Event Page
  mobile/src/assets/locales/ro/translation.json
  mobile/src/components/ReadOnlyElement.tsx
  mobile/src/components/TaskPill.tsx
  mobile/src/layouts/PageLayout.tsx
  mobile/src/screens/Event.tsx
Labels: enhancement :rocket:, front-end

#174 Feat[TEO-890] - Create Volunteer Profile
  mobile/src/assets/locales/ro/translation.json
  mobile/src/components/FormInput.tsx
  mobile/src/components/Input.tsx
  mobile/src/routes/Private.tsx
  mobile/src/screens/CreateVolunteer.tsx
Labels: enhancement :rocket:, front-end
