Repository code4romania/vic, pull requests merged in 2024-07, with the labels that each got.

#300 fix: [272] add deselect option for selects
  frontend/src/components/ActivityLogTable.tsx
  frontend/src/components/ContractsTable.tsx
  frontend/src/components/LineChartCard.tsx
  frontend/src/components/PieChartCard.tsx
  frontend/src/components/RsvpTable.tsx
  frontend/src/components/Select.tsx
  frontend/src/components/Tabs.tsx
  frontend/src/containers/OrganizationStructureSelect.tsx
  frontend/src/pages/ActivityTypes.tsx
  frontend/src/pages/Volunteers.tsx
  frontend/src/services/volunteer/volunteer.service.ts
Labels: enhancement :rocket:

#307 fix [#306]: update notifications preferences when first opening app && display modal if push notifications are not enabled
  mobile/src/assets/locales/en/translation.json
  mobile/src/assets/locales/ro/translation.json
  mobile/src/common/utils/notifications.ts
  mobile/src/contexts/notification/NotificationContextProvider.tsx
  mobile/src/screens/NotificationsSettings.tsx
Labels: bug :bug:, mobile-app

#308 fix: [305] reset filters on volunteers page
  frontend/src/pages/Volunteers.tsx
Labels: bug :bug:
